// ============================================================
// MOCK DATA — Live Activities
// WhaleCopy AI — No real transactions
// ============================================================

export type ActivityAction = "bought" | "sold" | "added" | "warning";

export interface ActivityData {
  id: string;
  walletLabel: string;
  walletAddress: string;
  action: ActivityAction;
  token: string;
  amount: string;
  valueUsd: number;
  timestamp: string;
  description: string;
  txHash: string;
}

export const activities: ActivityData[] = [
  {
    id: "a1",
    walletLabel: "Whale Alpha",
    walletAddress: "7xKQ...92A",
    action: "bought",
    token: "SOL",
    amount: "12,500",
    valueUsd: 2187500,
    timestamp: "2 min ago",
    description: "Large accumulation detected — 3rd buy in 2 hours",
    txHash: "4xK9...mB2r",
  },
  {
    id: "a2",
    walletLabel: "Smart Money #1",
    walletAddress: "3dFR...B8z",
    action: "added",
    token: "JUP",
    amount: "450,000",
    valueUsd: 585000,
    timestamp: "5 min ago",
    description: "Added to existing position via Jupiter swap",
    txHash: "7tLm...nC4y",
  },
  {
    id: "a3",
    walletLabel: "Degen King",
    walletAddress: "9pLM...K2r",
    action: "bought",
    token: "WIF",
    amount: "890,000",
    valueUsd: 1780000,
    timestamp: "8 min ago",
    description: "New position opened — momentum play",
    txHash: "2pNh...fD6a",
  },
  {
    id: "a4",
    walletLabel: "MEV Bot #7",
    walletAddress: "8wRJ...C4y",
    action: "sold",
    token: "BONK",
    amount: "45,000,000",
    valueUsd: 945000,
    timestamp: "12 min ago",
    description: "Full exit — sold entire BONK position",
    txHash: "9cYt...bE3w",
  },
  {
    id: "a5",
    walletLabel: "Institutional Acc",
    walletAddress: "5tVN...Q9x",
    action: "bought",
    token: "RAY",
    amount: "125,000",
    valueUsd: 437500,
    timestamp: "15 min ago",
    description: "Steady DCA — weekly scheduled buy",
    txHash: "3gZp...hK7m",
  },
  {
    id: "a6",
    walletLabel: "DeFi Farmer",
    walletAddress: "2kNH...P6a",
    action: "added",
    token: "ORCA",
    amount: "85,000",
    valueUsd: 340000,
    timestamp: "18 min ago",
    description: "Added liquidity to ORCA/SOL pool",
    txHash: "6wRj...dC4y",
  },
  {
    id: "a7",
    walletLabel: "Whale Alpha",
    walletAddress: "7xKQ...92A",
    action: "warning",
    token: "PYTH",
    amount: "320,000",
    valueUsd: 192000,
    timestamp: "22 min ago",
    description: "Exit signal — dumped 80% of PYTH holdings",
    txHash: "1kNh...fP6a",
  },
  {
    id: "a8",
    walletLabel: "Smart Money #1",
    walletAddress: "3dFR...B8z",
    action: "bought",
    token: "RENDER",
    amount: "28,000",
    valueUsd: 252000,
    timestamp: "28 min ago",
    description: "AI narrative play — first entry into RENDER",
    txHash: "5tVn...jQ9x",
  },
  {
    id: "a9",
    walletLabel: "Degen King",
    walletAddress: "9pLM...K2r",
    action: "bought",
    token: "POPCAT",
    amount: "2,400,000",
    valueUsd: 1680000,
    timestamp: "31 min ago",
    description: "Meme coin snipe — early entry",
    txHash: "8xKX...mN4p",
  },
  {
    id: "a10",
    walletLabel: "Airdrop Hunter",
    walletAddress: "4gZP...L7m",
    action: "added",
    token: "JITO",
    amount: "15,000",
    valueUsd: 52500,
    timestamp: "35 min ago",
    description: "Staked JITO for MEV rewards",
    txHash: "0dFq...uB8z",
  },
  {
    id: "a11",
    walletLabel: "Sniper Bot",
    walletAddress: "Bx4F...7Kd",
    action: "warning",
    token: "SLERF",
    amount: "5,200,000",
    valueUsd: 312000,
    timestamp: "38 min ago",
    description: "Suspicious activity — rapid buy/sell pattern detected",
    txHash: "Ax7R...pQ3m",
  },
  {
    id: "a12",
    walletLabel: "Quiet Giant",
    walletAddress: "Qm8Y...3Nf",
    action: "bought",
    token: "SOL",
    amount: "8,000",
    valueUsd: 1400000,
    timestamp: "42 min ago",
    description: "Whale accumulation — silent large buy",
    txHash: "Zy2K...bN8v",
  },
  {
    id: "a13",
    walletLabel: "MEV Bot #7",
    walletAddress: "8wRJ...C4y",
    action: "sold",
    token: "WIF",
    amount: "1,200,000",
    valueUsd: 2400000,
    timestamp: "47 min ago",
    description: "Profit taking — sold at local top",
    txHash: "Kp3N...xW9q",
  },
  {
    id: "a14",
    walletLabel: "NFT Whale",
    walletAddress: "6cYT...E3w",
    action: "warning",
    token: "BONK",
    amount: "120,000,000",
    valueUsd: 2520000,
    timestamp: "52 min ago",
    description: "Massive dump incoming — moving tokens to exchange",
    txHash: "Rt6V...mJ2a",
  },
];
