// ============================================================
// MOCK DATA — Wallets
// WhaleCopy AI — No real wallets, no real addresses
// ============================================================

export type WalletTag = "watchlist" | "testing" | "good" | "rejected" | "neutral";

export interface WalletData {
  id: string;
  address: string;
  label: string;
  roi24h: number;
  realizedPnl: number;
  winRate: number;
  totalTrades: number;
  avgHoldTime: string;
  copyScore: number; // 0–100, how "copyable" the wallet is
  status: "active" | "inactive" | "new";
  tag: WalletTag;
  isTracked: boolean;
  riskScore: "Low" | "Medium" | "High";
  lastActive: string;
}

export const wallets: WalletData[] = [
  {
    id: "w1",
    address: "7xKQ...92A",
    label: "Whale Alpha",
    roi24h: 24.8,
    realizedPnl: 182400,
    winRate: 87.5,
    totalTrades: 342,
    avgHoldTime: "4.2h",
    copyScore: 92,
    status: "active",
    tag: "good",
    isTracked: true,
    riskScore: "Medium",
    lastActive: "2 min ago",
  },
  {
    id: "w2",
    address: "3dFR...B8z",
    label: "Smart Money #1",
    roi24h: 12.3,
    realizedPnl: 156800,
    winRate: 82.1,
    totalTrades: 218,
    avgHoldTime: "12.5h",
    copyScore: 88,
    status: "active",
    tag: "good",
    isTracked: true,
    riskScore: "Low",
    lastActive: "5 min ago",
  },
  {
    id: "w3",
    address: "9pLM...K2r",
    label: "Degen King",
    roi24h: 67.8,
    realizedPnl: 234500,
    winRate: 73.4,
    totalTrades: 891,
    avgHoldTime: "1.8h",
    copyScore: 65,
    status: "active",
    tag: "watchlist",
    isTracked: false,
    riskScore: "High",
    lastActive: "8 min ago",
  },
  {
    id: "w4",
    address: "5tVN...Q9x",
    label: "Institutional Acc",
    roi24h: 5.1,
    realizedPnl: 89300,
    winRate: 91.2,
    totalTrades: 67,
    avgHoldTime: "3.2d",
    copyScore: 95,
    status: "active",
    tag: "good",
    isTracked: true,
    riskScore: "Low",
    lastActive: "15 min ago",
  },
  {
    id: "w5",
    address: "8wRJ...C4y",
    label: "MEV Bot #7",
    roi24h: 142.5,
    realizedPnl: 198700,
    winRate: 95.8,
    totalTrades: 2341,
    avgHoldTime: "45s",
    copyScore: 30,
    status: "active",
    tag: "rejected",
    isTracked: false,
    riskScore: "High",
    lastActive: "1 min ago",
  },
  {
    id: "w6",
    address: "2kNH...P6a",
    label: "DeFi Farmer",
    roi24h: 8.9,
    realizedPnl: 72500,
    winRate: 78.9,
    totalTrades: 156,
    avgHoldTime: "8.1h",
    copyScore: 81,
    status: "active",
    tag: "testing",
    isTracked: true,
    riskScore: "Medium",
    lastActive: "18 min ago",
  },
  {
    id: "w7",
    address: "6cYT...E3w",
    label: "NFT Whale",
    roi24h: -4.2,
    realizedPnl: 45600,
    winRate: 65.2,
    totalTrades: 89,
    avgHoldTime: "2.4d",
    copyScore: 55,
    status: "inactive",
    tag: "rejected",
    isTracked: false,
    riskScore: "Medium",
    lastActive: "3 hours ago",
  },
  {
    id: "w8",
    address: "4gZP...L7m",
    label: "Airdrop Hunter",
    roi24h: 3.4,
    realizedPnl: 34200,
    winRate: 71.8,
    totalTrades: 423,
    avgHoldTime: "6.5h",
    copyScore: 72,
    status: "active",
    tag: "neutral",
    isTracked: false,
    riskScore: "Low",
    lastActive: "35 min ago",
  },
  {
    id: "w9",
    address: "Bx4F...7Kd",
    label: "Sniper Bot",
    roi24h: 89.2,
    realizedPnl: 312000,
    winRate: 68.3,
    totalTrades: 1520,
    avgHoldTime: "12min",
    copyScore: 40,
    status: "active",
    tag: "watchlist",
    isTracked: false,
    riskScore: "High",
    lastActive: "30s ago",
  },
  {
    id: "w10",
    address: "Qm8Y...3Nf",
    label: "Quiet Giant",
    roi24h: 2.1,
    realizedPnl: 520000,
    winRate: 93.7,
    totalTrades: 41,
    avgHoldTime: "7.8d",
    copyScore: 97,
    status: "new",
    tag: "testing",
    isTracked: false,
    riskScore: "Low",
    lastActive: "1 hour ago",
  },
];
